
include: package:very_good_analysis/analysis_options.yaml


language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    public_member_api_docs: false
    