name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  chopper: ^8.1.0
  flutter:
    sdk: flutter
  # Pretty chopper logger (local package)
  pretty_chopper_logger:
    path: ../

dev_dependencies:
  build_runner: ^2.5.4
  chopper_generator: ^8.1.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
