name: pretty_chopper_logger
description: Pretty Chopper logger is a Chopper interceptor that logs network calls in a pretty, easy to read format.
version: 1.0.8
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  chopper: ^7.0.9
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  flutter_lints: ^3.0.1




