name: pretty_chopper_logger
description: Pretty Chopper logger is a Chopper interceptor that logs network calls in a pretty, easy to read format.
version: 1.0.12
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"


dependencies:
  chopper: ^8.0.0
  http: ^1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator: ^8.0.0
  flutter_lints: ^4.0.0




