name: pretty_chopper_logger
description: Pretty Chopper logger is a Chopper interceptor that logs network calls in a pretty, easy to read format.
version: 1.2.2
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  chopper: ^8.0.3
  http: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  flutter_lints: ^5.0.0




