name: pretty_chopper_logger
description: Pretty Chopper logger is a Chopper interceptor that logs network
  calls in a pretty, easy to read format.
version: 1.3.0
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  chopper: ^8.1.0
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  build_runner: ^2.5.0
  chopper_generator: ^8.1.0
  very_good_analysis: ^9.0.0
