name: pretty_chopper_logger
description: Pretty Choppper logger is a Choppper interceptor that logs network calls in a pretty, easy to read format.
version: 1.0.0
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  chopper: ^6.1.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  flutter_lints: ^2.0.0




