name: pretty_chopper_logger
description: Pretty Choppper logger is a Choppper interceptor that logs network calls in a pretty, easy to read format.
version: 1.0.5
homepage: https://github.com/Arnooodles/pretty_chopper_logger

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  chopper: ^6.1.2
  http: ^0.13.6
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  chopper_generator: ^6.0.1
  flutter_lints: ^2.0.1




